services:
  minio:
    image: minio/minio:latest
    container_name: minio
    networks: [cluster]
    ports:
      - "${MINIO_CONSOLE_HOST_PORT:-9001}:9001"
      - "${MINIO_API_HOST_PORT:-9002}:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
