services:
  zeppelin:
    image: adbgonzalez/zeppelin:0.12.0
    container_name: zeppelin
    hostname: zeppelin
    networks: [cluster]
    depends_on:
      - resourcemanager
      - nodemanager
      - namenode
      - datanode
    ports:
      - "${ZEPPELIN_HOST_PORT:-8081}:8080"
    environment:
      ZEPPELIN_ADDR: 0.0.0.0
      ZEPPELIN_PORT: 8080
      MASTER: yarn
      HADOOP_CONF_DIR: /usr/local/hadoop/etc/hadoop
      ZEPPELIN_NOTEBOOK_DIR: /notebook
    volumes:
      - ./zeppelin-notebooks:/notebook
      - ./spark-conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./jars:/opt/spark/jars-extra:ro

