services:
  nifi:
    image: apache/nifi:2.5.0
    container_name: nifi
    hostname: nifi
    restart: unless-stopped
    networks: [cluster]
    depends_on:
      - minio
      - namenode
    ports:
      - "${NIFI_HOST_PORT:-9091}:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
      NIFI_WEB_HTTPS_HOST: 0.0.0.0
      NIFI_WEB_PROXY_HOST: ${NIFI_PROXY_HOST:-localhost:9091}

      SINGLE_USER_CREDENTIALS_USERNAME: ${NIFI_USER:-admin}
      SINGLE_USER_CREDENTIALS_PASSWORD: ${NIFI_PASS:-Admin.BDA123!}

      NIFI_JVM_HEAP_INIT: ${NIFI_HEAP_INIT:-512m}
      NIFI_JVM_HEAP_MAX: ${NIFI_HEAP_MAX:-2g}
      NIFI_STATELESS_ENABLED: "false"
      NIFI_WEB_HTTP_PORT: ""

    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_database:/opt/nifi/nifi-current/database_repository
      - ./nifi_extensions:/opt/nifi/nifi-current/nar_extensions
      - ./conf:/opt/hadoop/conf
volumes:
  nifi_state:
  nifi_logs:
  nifi_conf:
  nifi_flowfile:
  nifi_content:
  nifi_provenance:
  nifi_database:

